apiVersion: v1
kind: Secret
metadata:
  name: test-pxc-secrets
  namespace: portal
type: Opaque
stringData:
  root: "rootpass123"
  xtrabackup: "backuppass123"
  monitor: "monitorpass123"
  clustercheck: "clustercheckpass123"
  proxyadmin: "proxyadminpass123"
  operator: "operatorpass123"
  replication: "replicationpass123"
---
apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: test-pxc
  namespace: portal
spec:
  crVersion: 1.18.0
  allowUnsafeConfigurations: true
  secretsName: test-pxc-secrets
  
  initContainer:
    image: ghcr.io/gmautner/pxc-operator:K8SPS-632-test
  
  pxc:
    size: 1
    image: percona/percona-xtradb-cluster:8.0.42-33.1
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
    volumeSpec:
      persistentVolumeClaim:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi

  haproxy:
    enabled: true
    size: 1
    image: percona/haproxy:2.8.15
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

  proxysql:
    enabled: false

  logcollector:
    enabled: false

  pmm:
    enabled: false

  backup:
    image: percona/percona-xtrabackup:8.0.35-34.1
    pitr:
      enabled: true
      storageName: s3-pitr
      timeBetweenUploads: 60
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    storages:
      s3-backup:
        type: s3
        s3:
          bucket: lwsa-idp-testbed-dev-backup-eks-06-ttzun9n9/pxc/portal-test/backup
          credentialsSecret: portal-blueprint-backup-creds
          region: us-east-2
          endpointUrl: https://s3.us-east-2.amazonaws.com
      s3-pitr:
        type: s3
        s3:
          bucket: lwsa-idp-testbed-dev-backup-eks-06-ttzun9n9/pxc/portal-test/pitr
          credentialsSecret: portal-blueprint-backup-creds
          region: us-east-2
          endpointUrl: https://s3.us-east-2.amazonaws.com
